### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by Tjoosten** [jasoncostello/slate#15]
Maybe you can add scss files into this project. If you want i will write it out!

**Comment by jasoncostello** [comment]
Sorry @Tjoosten, I didn't see this until today. I was taking a break from code/computers because I hurt my back and was avoiding hunching over my laptop. 

Feel free to add the SCSS. When this was created, Jekyll didn't support it yet. 

Though, I am thinking of revising this design as it looks a bit outdated, and releasing a v.2 of Slate.

Sorry for the lag.

**Comment by Tjoosten** [comment]
U still need a scss version. If yes i can start writing on it.

2016-02-17 18:21 GMT+01:00 Jason Costello notifications@github.com:
